FROM elixir:1.17-alpine

WORKDIR /sdk

RUN mix local.hex --force && mix local.rebar --force

COPY mix.exs mix.lock* ./
RUN mix deps.get

COPY lib/ lib/
COPY test/ test/

ENV MIX_ENV=test

CMD ["mix", "test", "--trace"]
